### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by jimfoye** [Excel-DNA/IntelliSense#66]
Just FYI.

ExcelDna.IntelliSense Warning: 4 : PopupList UpdateSelectedItem - IsVisible but GetListViewSelectedItemInfo failed 

ExcelDna.IntelliSense Warning: 6 : FormulaEditTextChange with no arguments tooltip !?

**Comment by jimfoye** [comment]
@govert Thanks. Here is another one, this one looks more serious:

ExcelDna.IntelliSense Warning: 2 : SingleThreadSynchronizationContext ### Unhandled exception (Thread 11) - System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Post(SendOrPostCallback d, Object state)
   at ExcelDna.IntelliSense.UIMonitor.OnStateChanged(UIState newStateOrNull)
   at ExcelDna.IntelliSense.UIMonitor._formulaEditWatcher_StateChanged(Object sender, StateChangeEventArgs args)
   at ExcelDna.IntelliSense.FormulaEditWatcher.OnStateChanged(StateChangeType stateChangeType)
   at ExcelDna.IntelliSense.FormulaEditWatcher.UpdateEditState(Boolean moveOnly)
   at ExcelDna.IntelliSense.FormulaEditWatcher.<UpdateEditStateDelayed>b__37_0(Object _)
   at ExcelDna.IntelliSense.SingleThreadSynchronizationContext.RunOnCurrentThread()

I'm on Excel-DNA .34.6 and Intellisense 1.1.0.

**Comment by govert** [comment]
@jimfoye Indeed. That's a class of problem I cause by changes in an earlier version, and that I tried to fix for v 1.1.0. I must have missed a case, and will have a look.

**Comment by jimfoye** [comment]
![capture1](https://user-images.githubusercontent.com/4249676/42902674-13175620-8a95-11e8-843d-42a3d2763621.PNG)

Here's another one you may care about. Visual Studio froze when I tried to kill Excel, so I couldn't copy the text, I'm attaching a screenshot instead.

**Comment by jimfoye** [comment]
I have not seen these warnings in quite a while. Maybe it's OK to close this.
