### ISSUE TITLE
Intellisense initialization crash

### ISSUE THREAD

**Issue by blurt** [Excel-DNA/IntelliSense#75]
Some users have experienced this issue on startup or after locking their computer.
This is a particularly nasty bug because client code cannot handle this exception and it takes down the entire app.

System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at ExcelDna.IntelliSense.Win32Helper.GetFocusedWindowHandle()
   at ExcelDna.IntelliSense.WindowWatcher.TryInitialize()
   at ExcelDna.IntelliSense.UIMonitor.RunUIAutomation()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by govert** [comment]
Can you confirm the exact IntelliSense version that this is happening with?

**Comment by govert** [comment]
The pull request https://github.com/Excel-DNA/IntelliSense/pull/58 concerned the same error.

**Comment by blurt** [comment]
Hi Govert,

This was reproduced using version 1.0.6, which did not include the PR that you mentioned. I will upgrade to the latest.

One concern that remains: #58 addresses the Win32Exception that is thrown in code (throw new Win32Exception()) but the exception that I noticed includes a message and error code -- perhaps the exception is coming from one of the P/Invoke calls? (GetGUIThreadInfo, GetWindowThreadProcessId, or GetCurrentProcessId).

Thanks

**Comment by govert** [comment]
You're seeing the magical behaviour of `new Win32Exception()`: "Initializes a new instance of the Win32Exception class with the last Win32 error that occurred."

See: 
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.win32exception.-ctor?view=netframework-4.7.2#System_ComponentModel_Win32Exception__ctor

Other error related to the 32-bit / 64-bit mismatch that causes this error have also been addressed.

I'd certainly be interested if you can reproduce this crash with the current version.

**Comment by blurt** [comment]
I will let you know if it's reproducible in the latest version, will close the issue in the meantime.
Thanks for your swift responses, and congratulations on a wonderful framework! Your work is very much appreciated.
